apiVersion: 'apps/v1'
kind: 'Deployment'
metadata:
  name: 'notes-api'
  namespace: 'default'
  labels:
    app: 'notes-api'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 'notes-api'
  template:
    metadata:
      labels:
        app: 'notes-api'
    spec:
      containers:
        - name: 'notes-api-1'
          image: 'asia-southeast2-docker.pkg.dev/YOUR_PROJECT_ID/repo/notes-api:latest'
