apiVersion: 'v1'
kind: 'Service'
metadata:
  name: 'notes-api-service'
  namespace: 'default'
  labels:
    app: 'notes-api'
spec:
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 5000
  selector:
    app: 'notes-api'
  type: 'LoadBalancer'
  loadBalancerIP: ''
